# Generated by Django 3.2.2 on 2021-05-11 23:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0007_auto_20210511_2333"),
        ("games", "0015_auto_20191005_1749"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={"verbose_name": "Game", "verbose_name_plural": "Games"},
        ),
        migrations.AlterModelOptions(
            name="gameresult",
            options={
                "verbose_name": "Game Result",
                "verbose_name_plural": "Game Results",
            },
        ),
        migrations.AlterModelOptions(
            name="gameresultdetail",
            options={
                "verbose_name": "Game Result Detail",
                "verbose_name_plural": "Game Result Details",
            },
        ),
        migrations.RemoveField(
            model_name="gameresult",
            name="result",
        ),
        migrations.AddField(
            model_name="game",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AddField(
            model_name="gameresult",
            name="chanllenger",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="challenger",
                to="players.player",
                verbose_name="Challenger",
            ),
        ),
        migrations.AddField(
            model_name="gameresult",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="gameresult",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AddField(
            model_name="gameresult",
            name="status",
            field=model_utils.fields.StatusField(
                choices=[(0, "dummy")],
                default="challenge",
                max_length=100,
                no_check_for_status=True,
                verbose_name="status",
            ),
        ),
        migrations.AddField(
            model_name="gameresult",
            name="status_changed",
            field=model_utils.fields.MonitorField(
                default=django.utils.timezone.now,
                monitor="status",
                verbose_name="status changed",
            ),
        ),
        migrations.AddField(
            model_name="gameresultdetail",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="gameresultdetail",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="code",
            field=models.CharField(
                max_length=4, unique=True, verbose_name="Code"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="description",
            field=models.CharField(
                max_length=250, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="gameresult",
            name="end",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="end"
            ),
        ),
        migrations.AlterField(
            model_name="gameresult",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game",
                to="games.game",
                verbose_name="Game",
            ),
        ),
        migrations.AlterField(
            model_name="gameresult",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="gameresult",
            name="start",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="start"
            ),
        ),
        migrations.AlterField(
            model_name="gameresult",
            name="winner",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="winner",
                to="players.player",
                verbose_name="Winner",
            ),
        ),
        migrations.AlterField(
            model_name="gameresultdetail",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="gameresultdetail",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player",
                to="players.player",
                verbose_name="Player",
            ),
        ),
        migrations.AlterField(
            model_name="gameresultdetail",
            name="points",
            field=models.IntegerField(default=0, verbose_name="Points"),
        ),
        migrations.AlterField(
            model_name="gameresultdetail",
            name="result",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_result",
                to="games.gameresult",
                verbose_name="Game Result",
            ),
        ),
    ]
