# Generated by Django 2.2.5 on 2019-09-30 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("nickname", models.CharField(max_length=50, unique=True)),
                ("level", models.IntegerField(default=0)),
                ("points", models.IntegerField(default=0)),
                (
                    "created",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2019, 9, 30, 16, 14, 46, 36847
                        ),
                        verbose_name="Creation date",
                    ),
                ),
            ],
        ),
    ]
