# Generated by Django 2.2.5 on 2019-09-30 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2019, 9, 30, 16, 14, 52, 216018),
                verbose_name="Creation date",
            ),
        ),
    ]
