# Generated by Django 3.2.2 on 2021-05-11 23:33

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0006_auto_20191005_1749"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="player",
            options={
                "verbose_name": "Player",
                "verbose_name_plural": "Players",
            },
        ),
        migrations.AddField(
            model_name="player",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="level",
            field=models.IntegerField(default=0, verbose_name="Level"),
        ),
        migrations.AlterField(
            model_name="player",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="player",
            name="nickname",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Nickname"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="points",
            field=models.IntegerField(default=0, verbose_name="Points"),
        ),
    ]
