# Generated by Django 2.2.5 on 2019-10-05 17:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_auto_20190930_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 5, 17, 15, 27, 97551, tzinfo=utc), verbose_name='Creation date'),
        ),
    ]
