# Generated by Django 2.2.5 on 2019-09-30 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_auto_20190930_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 30, 17, 57, 14, 198160), verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='end',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Game end date'),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 30, 17, 57, 14, 199119), verbose_name='Game start date'),
        ),
    ]
